# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Virgin Money Giving Digital Style Guide
email: james.lambert@virginmoney.com
description: Our style guide provides the design foundation for bringing our identity to life in a digital space.  It connects visual design with front end development through the Virgin Money digital framework.

# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://design.virginmoney.com" # the base hostname & protocol for your site
